/*
 * Banque de questions.
 * Format : [question, [BONNE réponse, mauvaise 1, mauvaise 2, mauvaise 3], difficulté]
 * La bonne réponse est toujours écrite en premier : les réponses sont mélangées au moment du jeu.
 * Difficulté : 1 = facile (questions 1-5), 2 = moyen (6-10), 3 = difficile (11-15).
 */
window.QUIZ_CATEGORIES = [
  { id: 'culture',  name: 'Culture générale', emoji: '🧠', color: '#4f8cff' },
  { id: 'cinema',   name: 'Cinéma',           emoji: '🎬', color: '#ff4d6d' },
  { id: 'musique',  name: 'Musique',          emoji: '🎵', color: '#c77dff' },
  { id: 'anime',    name: 'Anime & Manga',    emoji: '🍥', color: '#ff9f1c' },
  { id: 'sport',    name: 'Sports',           emoji: '⚽', color: '#2ec4b6' },
  { id: 'histoire', name: 'Histoire',         emoji: '🏛️', color: '#d4a373' },
  { id: 'geo',      name: 'Géographie',       emoji: '🌍', color: '#06d6a0' },
  { id: 'sciences', name: 'Sciences',         emoji: '🔬', color: '#48cae4' },
  { id: 'jeux',     name: 'Jeux vidéo',       emoji: '🎮', color: '#9b5de5' }
];

(function () {
  const Q = {
    culture: [
      ['Combien de jours compte une année bissextile ?', ['366', '365', '364', '367'], 1],
      ['Quelle couleur obtient-on en mélangeant du bleu et du jaune ?', ['Vert', 'Violet', 'Orange', 'Marron'], 1],
      ['Combien de côtés possède un hexagone ?', ['6', '5', '7', '8'], 1],
      ['Qui a peint « La Joconde » ?', ['Léonard de Vinci', 'Michel-Ange', 'Raphaël', 'Botticelli'], 1],
      ['Quelle est la monnaie du Japon ?', ['Le yen', 'Le won', 'Le yuan', 'Le baht'], 1],
      ['Quel est l\'animal terrestre le plus rapide ?', ['Le guépard', 'Le lion', 'L\'antilope', 'Le lévrier'], 1],
      ['Combien de lettres compte l\'alphabet français ?', ['26', '24', '28', '25'], 1],
      ['Qui a écrit « Les Misérables » ?', ['Victor Hugo', 'Émile Zola', 'Honoré de Balzac', 'Gustave Flaubert'], 2],
      ['Quel métal est liquide à température ambiante ?', ['Le mercure', 'Le plomb', 'L\'étain', 'Le zinc'], 2],
      ['Quelle est la langue la plus parlée au monde en nombre de locuteurs natifs ?', ['Le mandarin', 'L\'anglais', 'L\'espagnol', 'L\'hindi'], 2],
      ['Combien d\'os compte le squelette d\'un adulte ?', ['206', '186', '212', '256'], 2],
      ['Quel est le plus petit pays du monde ?', ['Le Vatican', 'Monaco', 'Nauru', 'Saint-Marin'], 2],
      ['Combien de pièces possède chaque joueur au début d\'une partie d\'échecs ?', ['16', '12', '18', '20'], 2],
      ['Dans la mythologie grecque, qui est le dieu de la mer ?', ['Poséidon', 'Hadès', 'Arès', 'Apollon'], 2],
      ['Quel peintre s\'est coupé une partie de l\'oreille ?', ['Vincent van Gogh', 'Paul Gauguin', 'Claude Monet', 'Paul Cézanne'], 2],
      ['Qui a écrit « Cent ans de solitude » ?', ['Gabriel García Márquez', 'Pablo Neruda', 'Jorge Luis Borges', 'Mario Vargas Llosa'], 3],
      ['Quel philosophe a écrit « Ainsi parlait Zarathoustra » ?', ['Friedrich Nietzsche', 'Emmanuel Kant', 'Arthur Schopenhauer', 'Georg Hegel'], 3],
      ['Qui est l\'auteur de « L\'Art de la guerre » ?', ['Sun Tzu', 'Confucius', 'Lao-Tseu', 'Mencius'], 3],
      ['Dans la mythologie nordique, comment s\'appelle le marteau de Thor ?', ['Mjöllnir', 'Gungnir', 'Gram', 'Excalibur'], 3],
      ['Quel peintre a réalisé « Guernica » ?', ['Pablo Picasso', 'Salvador Dalí', 'Francisco de Goya', 'Joan Miró'], 3],
      ['Quelle romancière a créé le détective Hercule Poirot ?', ['Agatha Christie', 'Mary Higgins Clark', 'P. D. James', 'Dorothy L. Sayers'], 3]
    ],

    cinema: [
      ['Quel film de James Cameron raconte le naufrage d\'un paquebot en 1912 ?', ['Titanic', 'Avatar', 'Abyss', 'Poséidon'], 1],
      ['Comment s\'appelle l\'école de sorcellerie dans « Harry Potter » ?', ['Poudlard', 'Beauxbâtons', 'Durmstrang', 'Ilvermorny'], 1],
      ['Dans « Le Roi Lion », comment s\'appelle le père de Simba ?', ['Mufasa', 'Scar', 'Rafiki', 'Zazu'], 1],
      ['Quel acteur incarne le capitaine Jack Sparrow ?', ['Johnny Depp', 'Orlando Bloom', 'Brad Pitt', 'Leonardo DiCaprio'], 1],
      ['Quel super-héros est surnommé « l\'Homme d\'acier » ?', ['Superman', 'Batman', 'Iron Man', 'Captain America'], 1],
      ['Dans « Star Wars », qui est le père de Luke Skywalker ?', ['Dark Vador', 'Obi-Wan Kenobi', 'Yoda', 'L\'empereur Palpatine'], 1],
      ['Combien de films compte la trilogie « Le Seigneur des anneaux » de Peter Jackson ?', ['3', '2', '4', '6'], 1],
      ['Qui a réalisé « Pulp Fiction » ?', ['Quentin Tarantino', 'Martin Scorsese', 'Guy Ritchie', 'Robert Rodriguez'], 2],
      ['Quel film a remporté l\'Oscar du meilleur film en 2020 ?', ['Parasite', '1917', 'Joker', 'Once Upon a Time… in Hollywood'], 2],
      ['Quel acteur a joué le Joker dans « The Dark Knight » (2008) ?', ['Heath Ledger', 'Joaquin Phoenix', 'Jared Leto', 'Jack Nicholson'], 2],
      ['Quel studio a produit « Toy Story » ?', ['Pixar', 'DreamWorks', 'Illumination', 'Blue Sky'], 2],
      ['Quel film français de 2011 réunit Omar Sy et François Cluzet ?', ['Intouchables', 'Bienvenue chez les Ch\'tis', 'Le Dîner de cons', 'Les Visiteurs'], 2],
      ['Dans « Matrix », quelle pilule Neo choisit-il d\'avaler ?', ['La rouge', 'La bleue', 'La verte', 'La jaune'], 2],
      ['Quel réalisateur a signé « Inception », « Interstellar » et « Oppenheimer » ?', ['Christopher Nolan', 'Denis Villeneuve', 'David Fincher', 'Ridley Scott'], 2],
      ['Dans quel pays a été principalement tourné « Le Seigneur des anneaux » ?', ['Nouvelle-Zélande', 'Australie', 'Irlande', 'Islande'], 2],
      ['Qui a réalisé « 2001, l\'Odyssée de l\'espace » ?', ['Stanley Kubrick', 'Ridley Scott', 'Steven Spielberg', 'George Lucas'], 3],
      ['Quel acteur a remporté trois fois l\'Oscar du meilleur acteur ?', ['Daniel Day-Lewis', 'Jack Nicholson', 'Tom Hanks', 'Marlon Brando'], 3],
      ['Quel est le premier long-métrage d\'animation de Disney (1937) ?', ['Blanche-Neige et les Sept Nains', 'Pinocchio', 'Fantasia', 'Bambi'], 3],
      ['Quel film de 1927 est considéré comme le premier long-métrage parlant ?', ['Le Chanteur de jazz', 'Metropolis', 'Les Lumières de la ville', 'Nosferatu'], 3],
      ['Quel film a remporté l\'Oscar du meilleur film en 2024 ?', ['Oppenheimer', 'Barbie', 'Pauvres Créatures', 'Killers of the Flower Moon'], 3],
      ['Quel compositeur a signé la musique de « Star Wars » ?', ['John Williams', 'Hans Zimmer', 'Ennio Morricone', 'Howard Shore'], 3]
    ],

    musique: [
      ['Quel chanteur est surnommé le « King of Pop » ?', ['Michael Jackson', 'Elvis Presley', 'Prince', 'Freddie Mercury'], 1],
      ['Combien de cordes possède une guitare classique standard ?', ['6', '4', '5', '7'], 1],
      ['Quel groupe britannique était composé de John, Paul, George et Ringo ?', ['The Beatles', 'The Rolling Stones', 'Queen', 'The Who'], 1],
      ['Quelle chanteuse a sorti « Single Ladies » ?', ['Beyoncé', 'Rihanna', 'Shakira', 'Lady Gaga'], 1],
      ['Quel groupe a interprété « Bohemian Rhapsody » ?', ['Queen', 'Pink Floyd', 'Led Zeppelin', 'The Beatles'], 1],
      ['Quel genre musical Bob Marley a-t-il rendu célèbre dans le monde entier ?', ['Le reggae', 'La salsa', 'Le calypso', 'La bossa nova'], 1],
      ['De quel instrument Frédéric Chopin jouait-il principalement ?', ['Le piano', 'Le violon', 'La flûte', 'Le violoncelle'], 1],
      ['Qui chante « La Vie en rose » (1947) ?', ['Édith Piaf', 'Dalida', 'Barbara', 'Juliette Gréco'], 2],
      ['Quel est le vrai nom de Stromae ?', ['Paul Van Haver', 'Paul Van Dyk', 'Pierre Vandamme', 'Paul Vandenbroeck'], 2],
      ['Combien de symphonies Beethoven a-t-il composées ?', ['9', '5', '7', '12'], 2],
      ['Quel duo français a produit « Get Lucky » ?', ['Daft Punk', 'Justice', 'Air', 'Cassius'], 2],
      ['De quel pays vient le groupe ABBA ?', ['Suède', 'Norvège', 'Danemark', 'Finlande'], 2],
      ['Quel rappeur américain a sorti « The Marshall Mathers LP » ?', ['Eminem', '50 Cent', 'Dr. Dre', 'Jay-Z'], 2],
      ['Quel saxophoniste camerounais est célèbre pour « Soul Makossa » ?', ['Manu Dibango', 'Richard Bona', 'Petit-Pays', 'Charlotte Dipanda'], 2],
      ['Quel artiste nigérian chante « Calm Down » en duo avec Selena Gomez ?', ['Rema', 'Burna Boy', 'Wizkid', 'Davido'], 2],
      ['Quel compositeur a écrit « Les Quatre Saisons » ?', ['Antonio Vivaldi', 'Jean-Sébastien Bach', 'Wolfgang Amadeus Mozart', 'Georg Friedrich Haendel'], 2],
      ['Dans quel opéra de Bizet entend-on « L\'amour est un oiseau rebelle » ?', ['Carmen', 'La Traviata', 'Aida', 'Tosca'], 3],
      ['Combien de touches compte un piano standard ?', ['88', '76', '92', '84'], 3],
      ['En quelle année est sorti l\'album « Thriller » de Michael Jackson ?', ['1982', '1979', '1985', '1987'], 3],
      ['Quel rappeur français a sorti l\'album « Civilisation » en 2021 ?', ['Orelsan', 'Nekfeu', 'Booba', 'Damso'], 3],
      ['Quel guitariste a mis le feu à sa guitare sur scène au festival de Monterey en 1967 ?', ['Jimi Hendrix', 'Eric Clapton', 'Jimmy Page', 'Chuck Berry'], 3],
      ['Quel groupe a sorti l\'album « The Dark Side of the Moon » ?', ['Pink Floyd', 'Led Zeppelin', 'The Doors', 'Genesis'], 3],
      ['Quel musicien nigérian est considéré comme le père de l\'afrobeat ?', ['Fela Kuti', 'King Sunny Adé', 'Burna Boy', 'Youssou N\'Dour'], 3]
    ],

    anime: [
      ['Comment s\'appelle le héros de « Dragon Ball » ?', ['Son Goku', 'Vegeta', 'Naruto', 'Luffy'], 1],
      ['Quel est le rêve de Luffy dans « One Piece » ?', ['Devenir le Roi des pirates', 'Devenir Hokage', 'Devenir Maître Pokémon', 'Devenir le meilleur épéiste'], 1],
      ['Quel Pokémon accompagne Sacha partout ?', ['Pikachu', 'Salamèche', 'Évoli', 'Rondoudou'], 1],
      ['Quel démon est scellé dans le corps de Naruto ?', ['Kyûbi, le renard à neuf queues', 'Shukaku', 'Un dragon', 'Un loup à huit queues'], 1],
      ['Dans quel anime des Titans géants dévorent-ils l\'humanité ?', ['L\'Attaque des Titans', 'Tokyo Ghoul', 'Bleach', 'Death Note'], 1],
      ['Combien de Dragon Balls faut-il réunir pour invoquer Shenron ?', ['7', '5', '6', '9'], 1],
      ['Qui est le grand rival de Naruto ?', ['Sasuke Uchiha', 'Kakashi Hatake', 'Neji Hyûga', 'Rock Lee'], 1],
      ['Dans « Death Note », comment s\'appelle le shinigami qui accompagne Light ?', ['Ryûk', 'Rem', 'Sidoh', 'Gelus'], 2],
      ['Dans « One Piece », qui est l\'épéiste de l\'équipage de Luffy ?', ['Roronoa Zoro', 'Sanji', 'Usopp', 'Franky'], 2],
      ['Dans « Demon Slayer », quelle est la sœur de Tanjirô transformée en démon ?', ['Nezuko', 'Shinobu', 'Kanao', 'Mitsuri'], 2],
      ['Quel studio a produit « Mon voisin Totoro » ?', ['Studio Ghibli', 'Toei Animation', 'Madhouse', 'Studio Pierrot'], 2],
      ['Dans « Dragon Ball Z », à quel peuple appartient Goku ?', ['Les Saiyans', 'Les Namekiens', 'Les humains', 'Les Kaïoshins'], 2],
      ['Comment s\'appellent les deux frères de « Fullmetal Alchemist » ?', ['Edward et Alphonse Elric', 'Roy et Maes Hughes', 'Ling et Lan Fan', 'Scar et Greed'], 2],
      ['Dans « Jujutsu Kaisen », de quel fléau Yuji avale-t-il le doigt ?', ['Ryômen Sukuna', 'Mahito', 'Jôgo', 'Hanami'], 2],
      ['Dans « Hunter x Hunter », qui est le meilleur ami de Gon ?', ['Kirua', 'Kurapika', 'Leorio', 'Hisoka'], 2],
      ['Dans « Naruto », quelle organisation porte des manteaux à nuages rouges ?', ['L\'Akatsuki', 'L\'Anbu', 'Le village d\'Oto', 'La Racine'], 2],
      ['Quel mangaka a créé « One Piece » ?', ['Eiichirô Oda', 'Masashi Kishimoto', 'Akira Toriyama', 'Tite Kubo'], 2],
      ['Dans « My Hero Academia », quel pouvoir All Might transmet-il à Izuku ?', ['One For All', 'All For One', 'Full Cowl', 'Plus Ultra'], 2],
      ['Qui a réalisé « Le Voyage de Chihiro » ?', ['Hayao Miyazaki', 'Isao Takahata', 'Makoto Shinkai', 'Mamoru Hosoda'], 2],
      ['Qui est l\'auteur du manga « L\'Attaque des Titans » ?', ['Hajime Isayama', 'Kôhei Horikoshi', 'Gege Akutami', 'Tatsuki Fujimoto'], 3],
      ['En quelle année le premier épisode de l\'anime « Dragon Ball » a-t-il été diffusé au Japon ?', ['1986', '1984', '1989', '1990'], 3],
      ['Dans « Death Note », quel est le vrai nom de L ?', ['L Lawliet', 'Nate River', 'Mihael Keehl', 'Teru Mikami'], 3],
      ['Quel film de Makoto Shinkai (2016) raconte un échange de corps entre deux lycéens ?', ['Your Name', 'Les Enfants du temps', 'Suzume', '5 centimètres par seconde'], 3],
      ['Dans « Fullmetal Alchemist », quelle est la loi fondamentale de l\'alchimie ?', ['L\'échange équivalent', 'La transmutation humaine', 'La pierre philosophale', 'Le cercle parfait'], 3],
      ['Dans « Neon Genesis Evangelion », qui pilote l\'EVA-01 ?', ['Shinji Ikari', 'Asuka Langley', 'Rei Ayanami', 'Kaworu Nagisa'], 3],
      ['Dans « Bleach », comment s\'appelle le sabre des Shinigami ?', ['Zanpakutô', 'Bankai', 'Kidô', 'Reiatsu'], 3]
    ],

    sport: [
      ['Combien de joueurs compte une équipe de football sur le terrain ?', ['11', '10', '12', '9'], 1],
      ['Quel pays a remporté la Coupe du monde de football 2018 ?', ['La France', 'La Croatie', 'La Belgique', 'Le Brésil'], 1],
      ['Dans quel sport utilise-t-on un volant ?', ['Le badminton', 'Le tennis', 'Le squash', 'Le tennis de table'], 1],
      ['Quel athlète jamaïcain détient le record du monde du 100 m ?', ['Usain Bolt', 'Yohan Blake', 'Asafa Powell', 'Tyson Gay'], 1],
      ['Tous les combien d\'années ont lieu les Jeux olympiques d\'été ?', ['4 ans', '2 ans', '3 ans', '5 ans'], 1],
      ['Dans quelle ville se sont déroulés les Jeux olympiques d\'été 2024 ?', ['Paris', 'Los Angeles', 'Tokyo', 'Londres'], 1],
      ['Combien de joueurs par équipe sont sur le terrain au basket-ball ?', ['5', '6', '7', '4'], 1],
      ['Quel pays a remporté la Coupe du monde de football 2022 ?', ['L\'Argentine', 'La France', 'La Croatie', 'Le Maroc'], 2],
      ['Quel joueur a remporté le plus de Ballons d\'or ?', ['Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'], 2],
      ['Quel tournoi du Grand Chelem se joue sur terre battue ?', ['Roland-Garros', 'Wimbledon', 'L\'US Open', 'L\'Open d\'Australie'], 2],
      ['Quel joueur a remporté Roland-Garros 14 fois ?', ['Rafael Nadal', 'Roger Federer', 'Novak Djokovic', 'Björn Borg'], 2],
      ['Quel club a remporté le plus de Ligues des champions ?', ['Le Real Madrid', 'L\'AC Milan', 'Le Bayern Munich', 'Liverpool'], 2],
      ['Quel pays a remporté la CAN 2023 (jouée en 2024) ?', ['La Côte d\'Ivoire', 'Le Nigeria', 'Le Sénégal', 'Le Cameroun'], 2],
      ['Quel boxeur s\'appelait Cassius Clay avant de changer de nom ?', ['Muhammad Ali', 'Joe Frazier', 'George Foreman', 'Sugar Ray Leonard'], 2],
      ['Quel nageur détient le record de médailles olympiques ?', ['Michael Phelps', 'Mark Spitz', 'Ryan Lochte', 'Ian Thorpe'], 2],
      ['Quel pilote a remporté 7 titres de champion du monde de F1, comme Lewis Hamilton ?', ['Michael Schumacher', 'Ayrton Senna', 'Sebastian Vettel', 'Alain Prost'], 2],
      ['Quelle est la distance officielle d\'un marathon ?', ['42,195 km', '40 km', '42 km', '45,5 km'], 2],
      ['En quelle année ont eu lieu les premiers Jeux olympiques modernes ?', ['1896', '1900', '1888', '1912'], 3],
      ['Quel pays a remporté le plus de Coupes du monde de rugby ?', ['L\'Afrique du Sud', 'La Nouvelle-Zélande', 'L\'Australie', 'L\'Angleterre'], 3],
      ['Au golf, comment appelle-t-on un trou réussi en deux coups sous le par ?', ['Un eagle', 'Un birdie', 'Un bogey', 'Un albatros'], 3],
      ['Quel pays a accueilli la toute première Coupe du monde de football en 1930 ?', ['L\'Uruguay', 'Le Brésil', 'L\'Italie', 'La France'], 3],
      ['Combien de temps dure un round de boxe professionnelle ?', ['3 minutes', '2 minutes', '4 minutes', '5 minutes'], 3],
      ['Quel Camerounais a été élu quatre fois Ballon d\'or africain ?', ['Samuel Eto\'o', 'Roger Milla', 'Patrick Mboma', 'Rigobert Song'], 3],
      ['Quel pays détient le record de victoires à la Coupe d\'Afrique des nations ?', ['L\'Égypte', 'Le Cameroun', 'Le Ghana', 'Le Nigeria'], 3]
    ],

    histoire: [
      ['Qui fut le premier président des États-Unis ?', ['George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'], 1],
      ['En quelle année a commencé la Seconde Guerre mondiale ?', ['1939', '1914', '1945', '1941'], 1],
      ['Quel empereur français a été exilé sur l\'île de Sainte-Hélène ?', ['Napoléon Ier', 'Napoléon III', 'Louis XVIII', 'Charlemagne'], 1],
      ['Quelle civilisation a construit les pyramides de Gizeh ?', ['Les Égyptiens', 'Les Romains', 'Les Mayas', 'Les Grecs'], 1],
      ['En quelle année a eu lieu la prise de la Bastille ?', ['1789', '1799', '1776', '1804'], 1],
      ['Qui a été le premier homme à marcher sur la Lune ?', ['Neil Armstrong', 'Buzz Aldrin', 'Youri Gagarine', 'Michael Collins'], 1],
      ['Qui fut le premier président noir de l\'Afrique du Sud ?', ['Nelson Mandela', 'Desmond Tutu', 'Thabo Mbeki', 'Jacob Zuma'], 2],
      ['En quelle année Christophe Colomb a-t-il atteint l\'Amérique ?', ['1492', '1498', '1453', '1515'], 2],
      ['Quelle reine d\'Égypte fut l\'alliée de Jules César puis de Marc Antoine ?', ['Cléopâtre', 'Néfertiti', 'Hatchepsout', 'Néfertari'], 2],
      ['Quelle ville a été frappée par la première bombe atomique utilisée en guerre ?', ['Hiroshima', 'Nagasaki', 'Tokyo', 'Osaka'], 2],
      ['Qui fut la première femme à recevoir un prix Nobel ?', ['Marie Curie', 'Rosalind Franklin', 'Ada Lovelace', 'Irène Joliot-Curie'], 2],
      ['Comment s\'appelle la guerre civile qui a opposé le Nord et le Sud des États-Unis ?', ['La guerre de Sécession', 'La guerre d\'indépendance', 'La guerre de Cent Ans', 'La guerre froide'], 2],
      ['En quelle année l\'Homme a-t-il marché sur la Lune pour la première fois ?', ['1969', '1965', '1972', '1959'], 2],
      ['En quelle année est tombé le mur de Berlin ?', ['1989', '1991', '1987', '1985'], 2],
      ['Quel roi de France était surnommé le « Roi-Soleil » ?', ['Louis XIV', 'Louis XVI', 'François Ier', 'Henri IV'], 2],
      ['En quelle année le Cameroun (sous administration française) a-t-il obtenu son indépendance ?', ['1960', '1958', '1961', '1962'], 3],
      ['En quelle année a eu lieu la bataille de Waterloo ?', ['1815', '1805', '1812', '1821'], 3],
      ['Quel empire a été fondé par Soundiata Keïta ?', ['L\'Empire du Mali', 'L\'Empire songhaï', 'L\'Empire du Ghana', 'Le Royaume du Kongo'], 3],
      ['Qui fut le dernier tsar de Russie ?', ['Nicolas II', 'Alexandre III', 'Pierre le Grand', 'Ivan IV'], 3],
      ['En quelle année l\'Empire romain d\'Occident a-t-il chuté ?', ['476', '410', '395', '1453'], 3],
      ['Quel navigateur portugais a ouvert la route maritime vers l\'Inde en 1498 ?', ['Vasco de Gama', 'Fernand de Magellan', 'Bartolomeu Dias', 'Pedro Álvares Cabral'], 3]
    ],

    geo: [
      ['Quel est le plus long fleuve d\'Afrique ?', ['Le Nil', 'Le Congo', 'Le Niger', 'Le Zambèze'], 1],
      ['Quelle est la capitale de l\'Italie ?', ['Rome', 'Milan', 'Naples', 'Venise'], 1],
      ['Sur quel continent se trouve le Brésil ?', ['L\'Amérique du Sud', 'L\'Afrique', 'L\'Amérique du Nord', 'L\'Océanie'], 1],
      ['Quelle est la plus haute montagne du monde ?', ['L\'Everest', 'Le K2', 'Le Kilimandjaro', 'Le Mont Blanc'], 1],
      ['Quelle est la capitale du Cameroun ?', ['Yaoundé', 'Douala', 'Garoua', 'Bamenda'], 1],
      ['Quel est le plus grand océan du monde ?', ['L\'océan Pacifique', 'L\'océan Atlantique', 'L\'océan Indien', 'L\'océan Arctique'], 1],
      ['Quel océan sépare l\'Europe de l\'Amérique ?', ['L\'océan Atlantique', 'L\'océan Pacifique', 'L\'océan Indien', 'L\'océan Austral'], 1],
      ['Quelle est la capitale de l\'Australie ?', ['Canberra', 'Sydney', 'Melbourne', 'Perth'], 2],
      ['Quelle est la capitale du Canada ?', ['Ottawa', 'Toronto', 'Montréal', 'Vancouver'], 2],
      ['Quel est le plus grand pays du monde par sa superficie ?', ['La Russie', 'Le Canada', 'La Chine', 'Les États-Unis'], 2],
      ['Quel est le plus grand désert chaud du monde ?', ['Le Sahara', 'Le Kalahari', 'Le Gobi', 'Le désert d\'Arabie'], 2],
      ['Quel est le pays le plus peuplé du monde depuis 2023 ?', ['L\'Inde', 'La Chine', 'Les États-Unis', 'L\'Indonésie'], 2],
      ['Quel est le plus haut sommet d\'Afrique ?', ['Le Kilimandjaro', 'Le mont Kenya', 'Le mont Cameroun', 'Le Ras Dashen'], 2],
      ['Quel détroit sépare l\'Europe de l\'Afrique ?', ['Le détroit de Gibraltar', 'Le Bosphore', 'Le détroit de Messine', 'Le détroit d\'Ormuz'], 2],
      ['Quelle est la capitale du Burkina Faso ?', ['Ouagadougou', 'Bamako', 'Niamey', 'Bobo-Dioulasso'], 2],
      ['Quelle est la capitale de la Mongolie ?', ['Oulan-Bator', 'Astana', 'Bichkek', 'Tachkent'], 3],
      ['Quelle est la capitale du Kazakhstan ?', ['Astana', 'Almaty', 'Bichkek', 'Douchanbé'], 3],
      ['Quel est le plus grand lac d\'Afrique ?', ['Le lac Victoria', 'Le lac Tanganyika', 'Le lac Malawi', 'Le lac Tchad'], 3],
      ['Quel pays compte le plus de fuseaux horaires (territoires d\'outre-mer inclus) ?', ['La France', 'La Russie', 'Les États-Unis', 'La Chine'], 3],
      ['Où se trouve le point le plus profond des océans ?', ['La fosse des Mariannes', 'La fosse de Porto Rico', 'La fosse des Tonga', 'La fosse du Japon'], 3],
      ['Quel est le plus long fleuve d\'Europe ?', ['La Volga', 'Le Danube', 'Le Rhin', 'La Loire'], 3]
    ],

    sciences: [
      ['Quelle planète est surnommée la « planète rouge » ?', ['Mars', 'Vénus', 'Jupiter', 'Mercure'], 1],
      ['Quelle est la formule chimique de l\'eau ?', ['H₂O', 'CO₂', 'O₂', 'NaCl'], 1],
      ['Quel organe pompe le sang dans le corps ?', ['Le cœur', 'Le foie', 'Les poumons', 'Les reins'], 1],
      ['Combien de planètes compte le système solaire ?', ['8', '9', '7', '10'], 1],
      ['Qui a formulé la théorie de la relativité ?', ['Albert Einstein', 'Isaac Newton', 'Galilée', 'Nikola Tesla'], 1],
      ['Quel gaz les plantes absorbent-elles pour la photosynthèse ?', ['Le dioxyde de carbone', 'L\'oxygène', 'L\'azote', 'L\'hélium'], 1],
      ['Quelle est la plus grande planète du système solaire ?', ['Jupiter', 'Saturne', 'Neptune', 'Uranus'], 2],
      ['Quelle est la vitesse approximative de la lumière dans le vide ?', ['300 000 km/s', '30 000 km/s', '3 000 000 km/s', '150 000 km/s'], 2],
      ['Quel est l\'os le plus long du corps humain ?', ['Le fémur', 'Le tibia', 'L\'humérus', 'Le péroné'], 2],
      ['Qui a découvert la pénicilline ?', ['Alexander Fleming', 'Louis Pasteur', 'Robert Koch', 'Edward Jenner'], 2],
      ['Quel est le symbole chimique de l\'or ?', ['Au', 'Ag', 'Or', 'Go'], 2],
      ['Quel élément chimique porte le numéro atomique 1 ?', ['L\'hydrogène', 'L\'hélium', 'L\'oxygène', 'Le carbone'], 2],
      ['Quelle est l\'unité de mesure de la résistance électrique ?', ['L\'ohm', 'Le volt', 'L\'ampère', 'Le watt'], 2],
      ['Quelle particule de l\'atome porte une charge négative ?', ['L\'électron', 'Le proton', 'Le neutron', 'Le photon'], 2],
      ['Quelle est la planète la plus chaude du système solaire ?', ['Vénus', 'Mercure', 'Mars', 'Jupiter'], 3],
      ['Combien de chromosomes possède une cellule humaine non sexuelle ?', ['46', '23', '48', '44'], 3],
      ['Quel est le pH de l\'eau pure à 25 °C ?', ['7', '0', '14', '5'], 3],
      ['Qui a proposé le tableau périodique des éléments en 1869 ?', ['Dmitri Mendeleïev', 'Antoine Lavoisier', 'John Dalton', 'Niels Bohr'], 3],
      ['Quel gaz est le plus abondant dans l\'atmosphère terrestre ?', ['L\'azote', 'L\'oxygène', 'Le dioxyde de carbone', 'L\'argon'], 3],
      ['Combien de cœurs possède une pieuvre ?', ['3', '1', '2', '8'], 3]
    ],

    jeux: [
      ['Comment s\'appelle le célèbre plombier moustachu de Nintendo ?', ['Mario', 'Wario', 'Link', 'Kirby'], 1],
      ['Dans quel jeu construit-on un monde entier avec des blocs ?', ['Minecraft', 'Fortnite', 'FIFA', 'Tetris'], 1],
      ['Comment s\'appelle le hérisson bleu de SEGA ?', ['Sonic', 'Knuckles', 'Tails', 'Shadow'], 1],
      ['Quelle entreprise fabrique la PlayStation ?', ['Sony', 'Microsoft', 'Nintendo', 'Sega'], 1],
      ['Quel jeu « Battle Royale » a été créé par Epic Games ?', ['Fortnite', 'PUBG', 'Apex Legends', 'Warzone'], 1],
      ['Comment s\'appelle le frère de Mario ?', ['Luigi', 'Wario', 'Toad', 'Yoshi'], 1],
      ['Quel est le héros de la saga « The Legend of Zelda » ?', ['Link', 'Zelda', 'Ganondorf', 'Epona'], 2],
      ['Dans quelle franchise incarne-t-on le Master Chief ?', ['Halo', 'Call of Duty', 'Gears of War', 'Destiny'], 2],
      ['Combien de fantômes poursuivent Pac-Man ?', ['4', '3', '5', '6'], 2],
      ['Quel studio développe la série « Grand Theft Auto » ?', ['Rockstar Games', 'Ubisoft', 'Electronic Arts', 'Activision'], 2],
      ['Quel jeu a été inventé par le Soviétique Alekseï Pajitnov ?', ['Tetris', 'Pong', 'Space Invaders', 'Snake'], 2],
      ['Quel éditeur français est à l\'origine d\'« Assassin\'s Creed » ?', ['Ubisoft', 'Quantic Dream', 'Gameloft', 'Focus Entertainment'], 2],
      ['Comment s\'appelle le héros de « The Witcher » ?', ['Geralt de Riv', 'Ciri', 'Jaskier', 'Vesemir'], 2],
      ['Quelle console Nintendo est sortie en 2017 ?', ['La Switch', 'La Wii U', 'La 3DS', 'La GameCube'], 2],
      ['En quelle année la première PlayStation est-elle sortie au Japon ?', ['1994', '1996', '1992', '1998'], 3],
      ['Quel jeu a été élu « Jeu de l\'année » aux Game Awards 2023 ?', ['Baldur\'s Gate 3', 'Alan Wake 2', 'Zelda: Tears of the Kingdom', 'Marvel\'s Spider-Man 2'], 3],
      ['Quel jeu de FromSoftware a été élu « Jeu de l\'année » aux Game Awards 2022 ?', ['Elden Ring', 'Dark Souls III', 'Sekiro', 'Bloodborne'], 3],
      ['Quel Pokémon porte le numéro 001 du Pokédex ?', ['Bulbizarre', 'Salamèche', 'Carapuce', 'Pikachu'], 3],
      ['Quel est le jeu vidéo le plus vendu de tous les temps ?', ['Minecraft', 'GTA V', 'Wii Sports', 'Mario Kart 8'], 3],
      ['Quelle entreprise a fabriqué la console Dreamcast ?', ['Sega', 'Sony', 'Nintendo', 'Atari'], 3]
    ]
  };

  window.QUIZ_QUESTIONS = Object.entries(Q).flatMap(([cat, list]) =>
    list.map(([q, a, d], i) => ({ id: cat + '-' + i, cat, q, a, d }))
  );
})();
